;;; -*- lisp-data -*-
((bbdb)
 (breadcrumb :host github :repo "joaotavora/breadcrumb")
 (cape)
 (citar)
 (color-theme-sanityinc-tomorrow)
 (color-theme-sanityinc-solarized)
 (combobulate :host github :repo "mickeynp/combobulate")
 (consult)
 (corfu)
 (deft)
 (dumb-jump)
 (edit-indirect)
 (editorconfig)
 (ef-themes)
 (eglot)
 (embark)
 (embark-consult)
 (expand-region)
 (flymake-flycheck)
 (flymake-shellcheck)
 (format-all :host github :repo "lassik/emacs-format-all-the-code"
             :fork (:repo "tsilvap/emacs-format-all-the-code" :branch "develop"))
 (fullframe)
 (git-gutter-fringe)
 (git-link)
 (go-mode)
 (go-playground)
 (ibuffer-vc)
 (jenkinsfile-mode)
 (json-mode)
 (just-mode)
 (lua-mode)
 (magit)
 (marginalia)
 (markdown-mode)
 (multiple-cursors)
 (nginx-mode)
 (ob-go)
 (orderless)
 (org-journal)
 (org-roam)
 (org-roam-ui)
 (paredit)
 (paren-face)
 (pyvenv)
 (restclient)
 (rg)
 (setup)
 (sml-mode)
 (sudo-edit)
 (vertico)
 (web-mode)
 (which-key)
 (ws-butler)
 (yaml-mode))
