;;; -*- lisp-data -*-
(("Getting started" . "getting-started.html")
 ("Editor support" . "editor-support.html")
 ("Using Emacs as an IDE" . "emacs-ide.html")
 ("The LispWorks IDE" . "lispworks.html")
 ("Using VSCode with Alive" . "vscode-alive.html")
 ("Functions" . "functions.html")
 ("Data Structures" . "data-structures.html")
 ("Strings" . "strings.html")
 ("Regular Expressions" . "regexp.html")
 ("Numbers" . "numbers.html")
 ("Loops, iteration, mapping" . "iteration.html")
 ("Multidimensional Arrays" . "arrays.html")
 ("Dates and Times" . "dates_and_times.html")
 ("Pattern Matching" . "pattern_matching.html")
 ("Input/Output" . "io.html")
 ("Files and Directories" . "files.html")
 ("CLOS (the Common Lisp Object System)" . "clos.html")
 ("Packages" . "packages.html")
 ("Defining Systems" . "systems.html")
 ("Error and condition handling" . "error_handling.html")
 ("Debugging" . "debugging.html")
 ("Macros and Backquote" . "macros.html")
 ("Type System" . "type.html")
 ("Concurrency and Parallelism" . "process.html")
 ("Performance Tuning" . "performance.html")
 ("Testing and Continuous Integration" . "testing.html")
 ("Scripting. Building executables" . "scripting.html")
 ("Miscellaneous" . "misc.html")
 ("Interfacing with your OS" . "os.html")
 ("Databases" . "databases.html")
 ("Foreign Function Interfaces" . "ffi.html")
 ("GUI programming" . "gui.html")
 ("Sockets" . "sockets.html")
 ("WebSockets" . "websockets.html")
 ("Web development" . "web.html")
 ("Web Scraping" . "web-scraping.html")
 ("Using the Win32 API" . "win32.html"))
